#
#  .swiftlint.yml
#  ScribbleFoundation
# 
#  Copyright (c) 2024 ScribbleLabApp LLC. And the ScribbleFoundation
#                Authors - All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this
#     list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#  3. Neither the name of the copyright holder nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - trailing_newline
  - vertical_whitespace
  - type_name
  - trailing_comma
  - nesting
  - function_parameter_count
  - force_try
  - non_optional_string_data_conversion
  - file_length
opt_in_rules:
  - empty_count

excluded:
  - .swiftpm
  - .build
  - ./utils
  - Documentation.docc
  - ScribbleFoundationTests/
  - DerivedData

analyzer_rules:
  - explicit_self

allow_zero_lintable_files: false

strict: false

force_cast: warning
line_length: 156
type_body_length:
  - 300
  - 400
identifier_name:
  min_length:
    error: 2
  max_length: 30
  excluded:
    - i
    - o
    - id
    - URL
    - GlobalAPIKey
    - vm
    
custom_rules:
spaces_over_tabs:
   included: ".*\\.swift"
   name: "Spaces over Tabs"
   regex: "\t"
   message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
   severity: warning

# reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
reporter: "xcode"